### PR TITLE
Function as key support and dependency map

### LINKED ISSUE #7: Use shorthand properties
See https://babeljs.io/docs/plugins/transform-es2015-shorthand-properties/

Instead of

```
Vue.$ioc.register('Axios', Axios);
```
we can use

```
Vue.$ioc.register( { Axios } ) ;
```

And for injection instead of  `created(SomethingThatMayGetMangled) { }` we can use `created( { SomethingThatWontGetMangled }) { }`

### PR DESCRIPTION
**Pull request by JiLiZART**
Nice plugin! Cool work dude!

I added some enchancements

`register` function now can accept only one argument, dependency itself, all other can be extracted later
now you can pass dependencies map when register plugin

And I added some jsdoc, so I can easily make TypeScript typings later

Probably it can resolve https://github.com/dealloc/vuec/issues/7 issue

// PS Would be nice if someday CI build badges will appear in readme and .editor config, and ofc automatic build after success test pass

### CODE REVIEW

**Comment by dealloc** [comment]
Hey, thanks for the PR!
I'm gonna get CI set up first (see #9) and then hopefully Github will run it on this PR so you can see what I'd like changed :)

I think that's easier than me nitpicking here and then automating it a few hours later ;)

**Comment by JiLiZART** [comment]
Any news?

**Comment by dealloc** [comment]
I don't have much time lately, I'm in the process of rewriting the tests so they can run in CI, sorry for the delays

**Comment by dealloc** [comment]
Hey @JiLiZART just wanted to let you know I'm going to go ahead and merge this since I won't have the time to get CI and stuff up and running within reasonable time so that you can at least enjoy the fruits of your labour :)

**Pull request merged**
